import "./globals.css";
import SocialMediaItem from "./components/SocialMediaItem";
import { AOSInit } from "./AOS";
import { raleway } from "../fonts";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Mercato and Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <AOSInit />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
